export { default as Accordion, type Slide as AccordionSlide } from './Accordion/Accordion'
export { default as ContactForm } from './ContactForm/ContactForm'
export { default as Experience, type ExperienceType } from './Experience/Experience'
export { default as Footer } from './Footer/Footer'
export { default as FooterLink, type Props as FooterLinkType } from './FooterLink/FooterLink'
export { default as Formation, type Props as FormationType } from './Formation/Formation'
export { default as Header } from './Header/Header'
export { default as InteractiveGallery, selectionToIndex, type SelectionItem } from './InteractiveGallery/InteractiveGallery'
export { default as Nav } from './Nav/Nav'
export { default as NavItem, type Props as NavItemProps } from './NavItem/NavItem'
export { default as Skill, type SkillType } from './Skill/Skill'
export { default as SourceLink, SOURCE_LINKS, type Props as SourceLinkType } from './SourceLink/SourceLink'
export { default as StackedCarousel, type Image as CarouselImage } from './StackedCarousel/StackedCarousel'
export { default as TextCarousel } from './TextCarousel/TextCarousel'

export * from './sections'